image: ruby2.0.0
services:
  - mysql
env:
  - DB=mysql
cache:
  - /tmp/bundler
script:
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -h 127.0.0.1 -u root -e 'create database paper_trail_test;'; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -h 127.0.0.1 -u root -e 'create database paper_trail_bar; '; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -h 127.0.0.1 -u root -e 'create database paper_trail_foo; '; fi"
  - mkdir /tmp/bundler
  - bundle install --quiet --path /tmp/bundler
  - bundle exec rake DB=mysql
