image: ruby2.0.0
services:
  - postgres
script:
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -u root -e 'create database paper_trail_test;'; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -u root -e 'create database paper_trail_bar; '; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -u root -e 'create database paper_trail_foo; '; fi"
  - bundle
  - bundle exec rake DB=sqlite
  - bundle exec rake DB=mysql
