image: ruby2.0.0
services:
  - mysql
  - postgres
env:
script:
  - DB=mysql
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -h 127.0.0.1 -u root -e 'create database paper_trail_test;'; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -h 127.0.0.1 -u root -e 'create database paper_trail_bar; '; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -h 127.0.0.1 -u root -e 'create database paper_trail_foo; '; fi"
  - bundle
  - bundle exec rake
  - DB=postgres
  - sh -c "if [ \"$DB\" = 'postgres' ]; then createuser -s -r postgres; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_bar;'  -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database paper_trail_foo;'  -U postgres; fi"
  - bundle
  - bundle exec rake
